name = 'mist'
license = 'MIT'
licenselink = './LICENSE'
description = 'A simple hugo theme that influenced by astro-theme-typography'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/kurokuma-lab/hugo-theme-mist'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'minimal', 'simple', 'rss', 'syntax highlighting', 'tags', 'mermaid', 'maths']
features = ['blog', 'minimal', 'simple', 'rss', 'syntax highlighting', 'tags', 'mermaid', 'maths']

# If the theme has a single author
[author]
  name = 'Kurokuma-lab'
  homepage = 'https://github.com/kurokuma-lab'
